from __future__ import annotations

import os
import tomllib
from functools import lru_cache
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, model_validator
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource, SettingsConfigDict

from valocoach.core.exceptions import ConfigurationError

APP_DIR_NAME = ".valocoach"
CONFIG_FILE_ENV_VAR = "VALOCOACH_CONFIG_FILE"
HOME_ENV_VAR = "VALOCOACH_HOME"

DEFAULT_CONFIG_TEMPLATE = """# ValoCoach configuration
# Generated by `valocoach config init`

[paths]
# home = "~/.valocoach"

[ollama]
host = "http://127.0.0.1:11434"
model = "qwen3:8b"
request_timeout_seconds = 300.0

[coach]
temperature = 0.5
patch_version = "unknown"

[ui]
stream_refresh_per_second = 8
coach_border_style = "green"
show_thinking = false
"""


def _expand_path(path: Path | str) -> Path:
    return Path(path).expanduser().resolve()


def default_home_dir() -> Path:
    """Resolve the ValoCoach home directory."""
    return _expand_path(os.environ.get(HOME_ENV_VAR, str(Path.home() / APP_DIR_NAME)))


def config_file_path() -> Path:
    """Resolve the active config file path."""
    custom_path = os.environ.get(CONFIG_FILE_ENV_VAR)
    if custom_path:
        return _expand_path(custom_path)
    return default_home_dir() / "config.toml"


def load_toml_document(path: Path) -> dict[str, Any]:
    """Load a TOML document, returning an empty mapping if it does not exist."""
    if not path.exists():
        return {}
    with path.open("rb") as file_handle:
        loaded = tomllib.load(file_handle)
    if not isinstance(loaded, dict):
        raise ConfigurationError(f"Expected a table at the root of {path}.")
    return loaded


def _parse_scalar(value: str) -> Any:
    lowered = value.strip().lower()
    if lowered in {"true", "false"}:
        return lowered == "true"
    try:
        if "." in value:
            return float(value)
        return int(value)
    except ValueError:
        return value


def _serialize_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    return f'"{str(value)}"'


def _dump_toml(document: dict[str, Any]) -> str:
    lines: list[str] = []
    for section, values in document.items():
        if isinstance(values, dict):
            lines.append(f"[{section}]")
            for key, value in values.items():
                lines.append(f"{key} = {_serialize_scalar(value)}")
            lines.append("")
        else:
            lines.append(f"{section} = {_serialize_scalar(values)}")
    return "\n".join(lines).strip() + "\n"


class PathsSettings(BaseModel):
    """Filesystem locations used by the CLI."""

    home: Path = Field(default_factory=default_home_dir)
    data_dir: Path | None = None
    chroma_dir: Path | None = None
    sessions_dir: Path | None = None
    history_file: Path | None = None

    @model_validator(mode="after")
    def populate_defaults(self) -> PathsSettings:
        home = _expand_path(self.home)
        self.home = home
        self.data_dir = _expand_path(self.data_dir or home / "data")
        self.chroma_dir = _expand_path(self.chroma_dir or self.data_dir / "chroma")
        self.sessions_dir = _expand_path(self.sessions_dir or home / "sessions")
        self.history_file = _expand_path(self.history_file or home / ".history")
        return self


class OllamaSettings(BaseModel):
    """Local Ollama connection settings."""

    host: str = "http://127.0.0.1:11434"
    model: str = "qwen3:8b"
    request_timeout_seconds: float = 300.0


class CoachSettings(BaseModel):
    """Coach model parameters."""

    temperature: float = 0.5
    patch_version: str = "unknown"


class UISettings(BaseModel):
    """Rich UI tuning."""

    stream_refresh_per_second: int = 8
    coach_border_style: str = "green"
    show_thinking: bool = False


class TomlConfigSettingsSource(PydanticBaseSettingsSource):
    """Read settings from `~/.valocoach/config.toml`."""

    def get_field_value(self, field: FieldInfo, field_name: str) -> tuple[Any, str, bool]:
        document = load_toml_document(config_file_path())
        return document.get(field_name), field_name, False

    def __call__(self) -> dict[str, Any]:
        return load_toml_document(config_file_path())


class AppSettings(BaseSettings):
    """Application settings loaded from TOML and environment variables."""

    model_config = SettingsConfigDict(
        env_prefix="VALOCOACH_",
        env_nested_delimiter="__",
        extra="ignore",
    )

    paths: PathsSettings = Field(default_factory=PathsSettings)
    ollama: OllamaSettings = Field(default_factory=OllamaSettings)
    coach: CoachSettings = Field(default_factory=CoachSettings)
    ui: UISettings = Field(default_factory=UISettings)

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        return (
            init_settings,
            env_settings,
            TomlConfigSettingsSource(settings_cls),
            file_secret_settings,
        )

    def ensure_directories(self) -> None:
        """Create the runtime directories used by the CLI."""
        self.paths.home.mkdir(parents=True, exist_ok=True)
        self.paths.data_dir.mkdir(parents=True, exist_ok=True)
        self.paths.chroma_dir.mkdir(parents=True, exist_ok=True)
        self.paths.sessions_dir.mkdir(parents=True, exist_ok=True)
        self.paths.history_file.parent.mkdir(parents=True, exist_ok=True)


def ensure_config_file(*, force: bool = False) -> Path:
    """Write the default config template if needed."""
    path = config_file_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        raise ConfigurationError(
            f"Config file already exists at {path}. Use --force to overwrite it."
        )
    path.write_text(DEFAULT_CONFIG_TEMPLATE, encoding="utf-8")
    return path


def set_config_value(key: str, value: str) -> Path:
    """Update a dotted config key inside the TOML file."""
    path = config_file_path()
    document = load_toml_document(path)
    if not path.exists():
        ensure_config_file()
        document = load_toml_document(path)

    target = document
    path_parts = key.split(".")
    if not all(path_parts):
        raise ConfigurationError(f"Invalid config key: {key}")

    for section in path_parts[:-1]:
        next_value = target.setdefault(section, {})
        if not isinstance(next_value, dict):
            raise ConfigurationError(f"Cannot set nested key under scalar field `{section}`.")
        target = next_value

    target[path_parts[-1]] = _parse_scalar(value)
    path.write_text(_dump_toml(document), encoding="utf-8")
    return path


@lru_cache(maxsize=1)
def get_settings() -> AppSettings:
    """Return cached settings."""
    settings = AppSettings()
    settings.ensure_directories()
    return settings


def clear_settings_cache() -> None:
    """Clear the cached settings instance."""
    get_settings.cache_clear()
