"""string_timestamps_rounds_in_spawn

Revision ID: 9edf9a0a8f87
Revises: 67ef1fbd8424
Create Date: 2026-04-18 19:25:36.298259

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9edf9a0a8f87"
down_revision: str | Sequence[str] | None = "67ef1fbd8424"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rounds_in_spawn", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.alter_column(
            "started_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=False
        )

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.alter_column(
            "started_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "synced_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=False
        )

    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column(
            "last_match_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=False
        )

    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.alter_column(
            "started_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "completed_at", existing_type=sa.DATETIME(), type_=sa.String(), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.alter_column(
            "completed_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=True
        )
        batch_op.alter_column(
            "started_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=False
        )

    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=False
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=False
        )
        batch_op.alter_column(
            "last_match_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=True
        )

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.alter_column(
            "synced_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=False
        )
        batch_op.alter_column(
            "started_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=False
        )

    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.alter_column(
            "started_at", existing_type=sa.String(), type_=sa.DATETIME(), existing_nullable=False
        )
        batch_op.drop_column("rounds_in_spawn")

    # ### end Alembic commands ###
