"""initial_schema

Revision ID: 67ef1fbd8424
Revises:
Create Date: 2026-04-18 18:46:19.677644

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67ef1fbd8424"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("map_name", sa.String(), nullable=False),
        sa.Column("map_id", sa.String(), nullable=True),
        sa.Column("queue_id", sa.String(), nullable=False),
        sa.Column("is_ranked", sa.Boolean(), nullable=False),
        sa.Column("game_version", sa.String(), nullable=True),
        sa.Column("game_length_secs", sa.Integer(), nullable=False),
        sa.Column("season_short", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("rounds_played", sa.Integer(), nullable=False),
        sa.Column("red_score", sa.Integer(), nullable=False),
        sa.Column("blue_score", sa.Integer(), nullable=False),
        sa.Column("winning_team", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.create_table(
        "players",
        sa.Column("puuid", sa.String(), nullable=False),
        sa.Column("riot_name", sa.String(), nullable=False),
        sa.Column("riot_tag", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("account_level", sa.Integer(), nullable=False),
        sa.Column("current_tier", sa.Integer(), nullable=False),
        sa.Column("current_tier_patched", sa.String(), nullable=False),
        sa.Column("current_rr", sa.Integer(), nullable=False),
        sa.Column("elo", sa.Integer(), nullable=False),
        sa.Column("peak_tier", sa.Integer(), nullable=False),
        sa.Column("peak_tier_patched", sa.String(), nullable=False),
        sa.Column("last_match_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("puuid"),
    )
    op.create_table(
        "sync_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("puuid", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("matches_fetched", sa.Integer(), nullable=False),
        sa.Column("matches_new", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_players",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("puuid", sa.String(), nullable=True),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("team", sa.String(), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("rounds_played", sa.Integer(), nullable=False),
        sa.Column("headshots", sa.Integer(), nullable=False),
        sa.Column("bodyshots", sa.Integer(), nullable=False),
        sa.Column("legshots", sa.Integer(), nullable=False),
        sa.Column("damage_dealt", sa.Integer(), nullable=False),
        sa.Column("damage_received", sa.Integer(), nullable=False),
        sa.Column("first_bloods", sa.Integer(), nullable=False),
        sa.Column("first_deaths", sa.Integer(), nullable=False),
        sa.Column("plants", sa.Integer(), nullable=False),
        sa.Column("defuses", sa.Integer(), nullable=False),
        sa.Column("competitive_tier", sa.Integer(), nullable=True),
        sa.Column("afk_rounds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "puuid", name="uq_match_player"),
    )
    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.create_index(
            "idx_mp_puuid_agent", ["puuid", "agent_name", "started_at"], unique=False
        )
        batch_op.create_index("idx_mp_puuid_started", ["puuid", "started_at"], unique=False)

    op.create_table(
        "rounds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("winning_team", sa.String(), nullable=False),
        sa.Column("result_code", sa.String(), nullable=False),
        sa.Column("bomb_planted", sa.Boolean(), nullable=False),
        sa.Column("plant_site", sa.String(), nullable=True),
        sa.Column("bomb_defused", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "round_number", name="uq_match_round"),
    )
    op.create_table(
        "kills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("time_in_round_ms", sa.Integer(), nullable=True),
        sa.Column("killer_puuid", sa.String(), nullable=False),
        sa.Column("victim_puuid", sa.String(), nullable=False),
        sa.Column("weapon_name", sa.String(), nullable=True),
        sa.Column("is_headshot", sa.Boolean(), nullable=False),
        sa.Column("assistants_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["round_id"], ["rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kills", schema=None) as batch_op:
        batch_op.create_index("idx_kills_killer", ["killer_puuid", "match_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kills", schema=None) as batch_op:
        batch_op.drop_index("idx_kills_killer")

    op.drop_table("kills")
    op.drop_table("rounds")
    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.drop_index("idx_mp_puuid_started")
        batch_op.drop_index("idx_mp_puuid_agent")

    op.drop_table("match_players")
    op.drop_table("sync_log")
    op.drop_table("players")
    op.drop_table("matches")
    # ### end Alembic commands ###
